import os

from dotenv import load_dotenv
from pydantic_settings import BaseSettings, SettingsConfigDict
from utils.enums import OAuthProvider

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

load_dotenv()


class AuthSettings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="auth_")
    dev_enviroment: bool = False
    service_name: str = "auth_service"
    redis_host: str = ...
    redis_port: int = ...
    db_name: str = ...
    db_host: str = ...
    db_port: int = ...
    db_user: str = ...
    db_password: str = ...
    db_engine_echo: bool = ...
    send_service_api_key: str = ...
    send_service_url: str = ...
    send_login_template: str = ...
    send_signup_template: str = ...
    superuser_username: str = ...
    superuser_password: str = ...
    superuser_first_name: str = ...
    superuser_last_name: str = ...
    superuser_email: str = ...
    superuser_organization: str = ...
    secret_key: str = ...
    access_token_expire_minutes: int = ...
    refresh_token_expire_minutes: int = ...
    algorithm: str = ...
    yandex_auth_url: str = ...
    yandex_token_url: str = ...
    yandex_client_id: str = ...
    yandex_redirect_uri: str = ...
    yandex_client_secret: str = ...
    yandex_user_info_url: str = ...
    jaeger_host: str = ...
    jaeger_port: int = ...
    enable_tracer: bool = False
    logstash_host: str = ...
    logstash_port: int = ...
    smtp_host: str = ...
    smtp_port: int = ...
    smtp_username: str = ...
    smtp_password: str = ...
    smtp_from_email: str = ...
    token_issuer: str = ...
    token_audience: str = ...
    request_id_excluded_urls: list[str] = ["/api/v1/auth/health"]

    @property
    def db_full_url(self):
        return f"postgresql+asyncpg://{self.db_user}:{self.db_password}@{self.db_host}:{self.db_port}/{self.db_name}"

    def access_token_expire_seconds(self):
        return self.access_token_expire_minutes * 60

    def oauth_url(self, provider: OAuthProvider):
        if provider == OAuthProvider.YANDEX:
            return (
                f"{self.yandex_auth_url}?response_type=code&"
                f"client_id={self.yandex_client_id}"
                f"&redirect_uri={self.yandex_redirect_uri}"
            )
        return None


settings = AuthSettings()
